version: "3.3"
services:
  web:
    image: node:16
    container_name: descaptcha
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "yarn install && yarn start"
    ports:
      - 3333:3333
    depends_on:
      - "mysql"
    networks:
      - default

  mysql:
    container_name: descaptcha_mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=descaptcha
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    container_name: descaptcha_phpmyadmin
    image: phpmyadmin
    ports:
      - 3000:80
    environment:
      - PMA_HOST=descaptcha_mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - default

volumes:
  data:
